name: example
description: A new Flutter project.
version: 1.0.0
homepage: https://github.com/Eagle6789/flutter_file_utils
author: Mohamed Naga <me.dev6789@gmail.com>

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.0.0
  path: ^1.8.2
  path_provider: ^2.0.11
  flutter_file_utils:
    path: ../