name: flutter_file_utils
description: Helper tools for managing files on Android
version: 0.2.0
#author: Mohamed Naga <me49544@gmail.com>
homepage: https://github.com/nagakm/flutter_file_utils

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.2
  path_provider: ^2.0.11
  package_info_plus: ^1.4.3+1

